name: Publish Mod

# Run when a new release is... released
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@bc4f63784f3519bcb513f012829c2af8a03f0818
        with:
          namespace: Phyore # the thunderstore 'team' to publish under
          description: Test Modpack 
          token: ${{ secrets.THUNDERSTORE_SERVICE_KEY }}
          name: PhyPack # the name of the package
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: lethal-company
          categories: | # <-- notice this pipe character
            modpacks
